language: java
script: ./gradlew check && ./.travis/releaseOnTag.sh
env:
  global:
  - secure: OiealYgHsQq4SqWpSHq7iSaaDg4wKAj2M7E8/l38lF32ULHwq59zoJI8PvT+kZU7odF4B4kZhhVAPEQAl9HxtmezyU2LWI2vsqGs+jFvjdAIaAlenEt1bApyMw4WCoTrcgjBXCInYqiTftRSTe5XTPHsQ3AjEysOB5h5SKJIu4U=
  - secure: gdKonzLCSUvvxXJrj3h8bgNcetAmb363t6C0q5IuxhctH4p2FaVMBPeOb05qWPnaRtHi2Y6mrFoqV5cO8/f9E2ljr+QQdd9RlQmhEXmlxU8FBeMkOmM7WZnqit0k2IRoX5BjZzmIjKq3/F+ZHkPq/uxEZCpO5guEcAfYc5FmF2o=
  - secure: igk/MRoV6OldrExDWhDfesdr3R1VIyUyByzwGlIB3KvSJW0v2JNUO3bhoi/7k32MGzChzWlVh3FbE3fcLe+JmtHoB/MhK8GRaguLA2Dh9kL8zmrzYzG8dH+trLPbcy1IuGW+0dJTBw1da9sw8jt5e2zZY4qmzP4TH0W3fkLbKG4=
